version: '3.7'
services:

  web:
    build: .
    container_name: "web"
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    # working_dir: /code
    volumes:
      - ./code:/code
      - ./requirements.txt:/code/requirements.txt
    # environment: 
    #   PYTHONUSERBASE: /pip-lib
    depends_on:
      - db
    
  db:
    image: mysql:5.7
    container_name: "db"
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    # volumes:
    #   - ./db:/var/lib/mysql